Adding forbidden flags checking logic (#176)
Adding forbidden flags checking logic (as per B2CA-1914)

diff --git a/.github/workflows/_check_makefile.yml b/.github/workflows/_check_makefile.yml
--- a/.github/workflows/_check_makefile.yml
+++ b/.github/workflows/_check_makefile.yml
@@ -12,6 +12,11 @@ on:
         required: false
         default: ${{ github.repository }}
         type: string
+      builder:
+        description: "The docker image to build the application in (defaults to ledger-app-builder-lite)"
+        required: false
+        default: 'ledger-app-builder-lite'
+        type: string
       repo_name:
         description: 'The name of the app repository to check. Defaults to the workflow caller repository name'
         required: false
@@ -37,13 +42,31 @@ env:
   RUN_FOR_DEVICES: ${{ inputs.run_for_devices }}
 
 jobs:
+  call_get_app_metadata:
+    # This job digests inputs and repository metadata provided by the `ledger_app.toml` manifest
+    # file, in order to output relevant directories, compatible devices, and other variables needed
+    # by following jobs.
+    name: Retrieve application metadata
+    uses: ./.github/workflows/_get_app_metadata.yml
+    with:
+      app_repository: ${{ inputs.app_repository }}
+      app_branch_name: ${{ inputs.app_branch_name }}
+      compatible_devices: ${{ inputs.run_for_devices }}
+      flags: ${{ inputs.flags }}
+      use_case: ${{ inputs.use_case }}
+    secrets:
+      token: ${{ secrets.token }}
+
   check_makefile:
     name: Check Makefile
+    needs: call_get_app_metadata
     strategy:
       fail-fast: false
       matrix:
         device: ${{ fromJSON(inputs.run_for_devices) }}
     runs-on: ubuntu-22.04
+    container:
+      image: ghcr.io/ledgerhq/ledger-app-builder/${{ inputs.builder }}:latest
 
     steps:
       - name: Clone ledger-app-workflows repository
@@ -65,6 +88,56 @@ jobs:
         with:
           name: ${{ inputs.download_manifest_artifact_name }}
           path: ${{ inputs.download_manifest_artifact_name }}
+
+      - name: Set device-specific environment variables
+        if: ${{ needs.call_get_app_metadata.outputs.is_rust == 'false' }}
+        shell: bash
+        run: |
+          eval "BOLOS_SDK=\$$(echo ${{ matrix.device }} | tr '[:lower:]' '[:upper:]')_SDK"
+          echo "BOLOS_SDK=${BOLOS_SDK}" >> "${GITHUB_ENV}"
+          echo "BOLOS_SDK will be set to: ${BOLOS_SDK}"
+
+      - name: Check for forbidden flags
+        id: check-no-debug-flag
+        shell: bash
+        if: ${{ needs.call_get_app_metadata.outputs.is_rust == 'false' }}
+        working-directory: app-repository
+        run: |
+          forbidden_flags=$(jq -r '.forbidden.c[]' ../ledger-app-workflows/config/forbidden-flags.json)
+
+          BUILD_DEVICE_NAME="${{ matrix.device }}"
+          BUILD_DEVICE_NAME="${BUILD_DEVICE_NAME/sp/s2}"
+
+          entrypoint_filepath=$(grep -rP \
+                                         --exclude-dir='deps' \
+                                         --exclude-dir='tests' \
+                                         --exclude-dir='vendor' \
+                                         --include='*.c' \
+                                         '\b(app_)?main\s*\([^)]*\)' . | cut -d':' -f1 | head -n1)
+
+          entrypoint_filepath=${entrypoint_filepath#./}
+          entrypoint_filepath=${entrypoint_filepath%.c}.o
+
+          build_dir=$(ledger-manifest -ob ledger_app.toml)
+          if [ -z "${build_dir}" ]; then
+            echo "build directory not found in ledger_app.toml!" >&2
+            exit 1
+          fi
+
+          make ${{ needs.call_get_app_metadata.outputs.flags }} \
+               ${ADDITIONAL_ARGS} \
+               BOLOS_SDK="${BOLOS_SDK}" \
+               --dry-run build/${BUILD_DEVICE_NAME}/obj/app/${entrypoint_filepath} 2>&1 | tee -a build_dry_run_output.txt
+
+          for forbidden_flag in $forbidden_flags; do
+            echo "[INFO] Checking for forbidden flag $forbidden_flag"
+            if grep -q "$forbidden_flag" build_dry_run_output.txt; then
+              echo "[ERROR] Detected forbidden flag $forbidden_flag in build output. Aborting."
+              exit 1
+            else
+              echo "[INFO] Did not find forbidden flag $forbidden_flag in build output. Continuing."
+            fi
+          done
 
       - name: Run script
         run: |
