[add] 'test_dir' managed through the _get_app_metadata.yml workflow

diff --git a/.github/workflows/_get_app_metadata.yml b/.github/workflows/_get_app_metadata.yml
--- a/.github/workflows/_get_app_metadata.yml
+++ b/.github/workflows/_get_app_metadata.yml
@@ -7,16 +7,26 @@ on:
         description: |
           The relative path in the repository where the application is built from (defaults to ".").
 
-          If the application is configured with a 'ledger_app.toml' file at its root, this parameter
-          is ignored.
+          If the application is configured with a 'ledger_app.toml' manifest at its root, this
+          parameter is ignored.
         required: false
         default: .
         type: string
       compatible_devices:
         description: |
-          The list of device(s) supported by the application. Defaults to ["nanos", "nanox",
-          "nanosp", "stax"]), except if the application is configured with a 'ledger_app.toml' file
-          at its root.
+          The list of device(s) supported by the application.
+
+          Defaults to ["nanos", "nanox", "nanosp", "stax"]), except if the application is configured
+          with a 'ledger_app.toml' manifest at its root.
+        required: false
+        default: 'None'
+        type: string
+      pytest_directory:
+        description: |
+          The directory where the Python tests are stored (a `conftest.py` file is expected there).
+
+          If the application is configured with a 'ledger_app.toml' manifest at its root with a
+          'tests.pytest_directory' field, this parameter is ignored.
         required: false
         default: 'None'
         type: string
@@ -28,15 +38,15 @@ on:
         description: |
           Returns the relative 'build_directory' path, i.e the repository directory where can be
           found either the root 'Makefile' of a C app, or the Cargo.toml of a Rust app.
-
-          This information is deduced from the 'ledger_app.toml' manifest if present, else is
-          equivalent to the 'relative_app_directory'.
         value: ${{ jobs.fetch_metadata.outputs.build_directory }}
       compatible_devices:
         description:
           The list of device(s) supported by the application.
         value: ${{ jobs.fetch_metadata.outputs.compatible_devices }}
-
+      pytest_directory:
+        description: |
+          The directory where the Python tests are stored (a `conftest.py` file is expected there).
+        value: ${{ jobs.fetch_metadata.outputs.pytest_directory }}
 
 env:
   APP_MANIFEST: "ledger_app.toml"
@@ -56,6 +66,7 @@ jobs:
       - name: Gather application metadata, from inputs or 'ledger_app.toml'
         id: fetch_metadata
         run: |
+          pytest_directory='${{ inputs.pytest_directory }}';
           if [[ -f "$APP_MANIFEST" ]];
           then
               # 'ledger_app.toml' exists
@@ -64,17 +75,26 @@ jobs:
                   # legacy manifest -> Rust application
                   echo "Legacy manifest detected. Please update your manifest to the newest version";
                   # checking the manifest with the repo
-                  ledger-manifest --legacy --check . "$APP_MANIFEST"
+                  ledger-manifest --legacy --check . "$APP_MANIFEST";
                   echo "build_directory=$(ledger-manifest --legacy --output-build-directory $APP_MANIFEST)" >> $GITHUB_OUTPUT;
-                  compatible_devices='${{ inputs.compatible_devices }}'
+                  compatible_devices='${{ inputs.compatible_devices }}';
                   echo "is_rust=true" >> $GITHUB_OUTPUT;
               else
                   # classic manifest -> can be either C or Rust
                   echo "Classic manifest detected.";
                   # checking the manifest with the repo
-                  ledger-manifest --check . "$APP_MANIFEST"
+                  ledger-manifest --check . "$APP_MANIFEST";
                   echo "build_directory=$(ledger-manifest --output-build-directory $APP_MANIFEST)" >> $GITHUB_OUTPUT;
-                  compatible_devices="$(ledger-manifest --output-devices $APP_MANIFEST)"
+                  compatible_devices="$(ledger-manifest --output-devices $APP_MANIFEST)";
+
+                  set +e  # when [tests.pytest_directory] is not set, ledger-manifest fails
+                  temp="$(ledger-manifest --output-pytest-directory $APP_MANIFEST)";
+                  if [ $? -eq 0 ];
+                  then
+                      pytest_directory="${temp}";
+                  fi
+                  set -e
+
                   if [[ "$(ledger-manifest --output-sdk $APP_MANIFEST)" == "rust" ]];
                   then
                       echo "is_rust=true" >> $GITHUB_OUTPUT;
@@ -86,22 +106,24 @@ jobs:
               # No 'ledger_app.toml' -> C application
               echo "No manifest detected.";
               echo "build_directory=${{ inputs.relative_app_directory }}" >> $GITHUB_OUTPUT;
-              compatible_devices='${{ inputs.compatible_devices }}'
+              compatible_devices='${{ inputs.compatible_devices }}';
               echo "is_rust=false" >> $GITHUB_OUTPUT;
           fi
 
           if [[ "${compatible_devices}" == 'None' ]];
           then
               # no inputs and no classic manifest
-              compatible_devices='["nanos", "nanosp", "nanox", "stax"]'
+              compatible_devices='["nanos", "nanosp", "nanox", "stax"]';
           else
               if [[ '${{ inputs.compatible_devices }}' != 'None' ]];
               then
                   # in case classic manifest with devices, the input takes precedence on it
-                  compatible_devices='${{ inputs.compatible_devices }}'
+                  compatible_devices='${{ inputs.compatible_devices }}';
               fi
           fi
+
           echo "compatible_devices=${compatible_devices}" | sed 's/+/p/' >> $GITHUB_OUTPUT;
+          echo "pytest_directory=${pytest_directory}" >> $GITHUB_OUTPUT;
 
           echo "Inferred metadata:"
           cat $GITHUB_OUTPUT
@@ -110,3 +132,4 @@ jobs:
       is_rust: ${{ steps.fetch_metadata.outputs.is_rust }}
       compatible_devices: ${{ steps.fetch_metadata.outputs.compatible_devices }}
       build_directory: ${{ steps.fetch_metadata.outputs.build_directory }}
+      pytest_directory: ${{ steps.fetch_metadata.outputs.pytest_directory }}
diff --git a/.github/workflows/reusable_ragger_tests.yml b/.github/workflows/reusable_ragger_tests.yml
--- a/.github/workflows/reusable_ragger_tests.yml
+++ b/.github/workflows/reusable_ragger_tests.yml
@@ -20,8 +20,9 @@ on:
         default: .
         type: string
       test_dir:
-        description: 'The directory where the Python tests are stored (a `conftest.py` file is expected there). Required'
-        required: true
+        description: 'The directory where the Python tests are stored (a `conftest.py` file is expected there).'
+        required: false
+        default: 'None'
         type: string
       download_app_binaries_artifact:
         description: 'The name of the artifact containing the application binary file(s) to be tested. Required'
@@ -43,9 +44,11 @@ on:
         default: ''
         type: string
       run_for_devices:
-        description: 'The list of device(s) on which the test will run (defaults to ["nanos", "nanox", "nanosp", "stax"])'
+        description: |
+          The list of device(s) on which the test will run. Defaults to ["nanos", "nanox", "nanosp",
+          "stax"], except if the application is configured with a 'ledger_app.toml' file at its root.
         required: false
-        default: '["nanos", "nanox", "nanosp", "stax"]'
+        default: 'None'
         type: string
       upload_snapshots_on_failure:
         description: 'Enable or disable upload of tests snapshots if the job fails (defaults to true).'
@@ -59,15 +62,32 @@ on:
         type: string
 
 jobs:
+  call_get_app_metadata:
+    name: Retrieve application metadata
+    uses: ./.github/workflows/_get_app_metadata.yml
+    with:
+      relative_app_directory: ${{ inputs.relative_app_directory }}
+      compatible_devices: ${{ inputs.run_for_devices }}
+      pytest_directory: ${{ inputs.test_dir }}
+
   ragger_tests:
     name: Functional tests with Ragger
+    needs: call_get_app_metadata
     strategy:
       fail-fast: false
       matrix:
-        device: ${{ fromJSON(inputs.run_for_devices) }}
+        device: ${{ fromJSON(needs.call_get_app_metadata.outputs.compatible_devices) }}
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check metadata
+        run: |
+          if [[ '${{ needs.call_get_app_metadata.outputs.pytest_directory }}' == 'None' ]];
+          then
+              >&2 echo "ERROR: This workflow either needs a 'ledger_app.toml' manifest with a 'tests.pytest_directory' section, or be configured with a valid 'test_dir' parameter";
+              exit 1;
+          fi
+
       - name: Clone
         uses: actions/checkout@v3
         with:
@@ -79,7 +99,7 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: ${{ inputs.download_app_binaries_artifact }}
-          path: ${{ inputs.relative_app_directory }}/build/
+          path: ${{ needs.call_get_app_metadata.outputs.build_directory }}/build/
 
       - name: Download additional app binaries if required
         if: ${{ inputs.additional_app_binaries_artifact != '' }}
@@ -93,22 +113,22 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: ${{ inputs.lib_binaries_artifact }}
-          path: ${{ inputs.test_dir }}/lib_binaries/
+          path: ${{ needs.call_get_app_metadata.outputs.pytest_directory }}/lib_binaries/
 
       - name: Install tests dependencies
         run: |
           sudo apt-get update && sudo apt-get install -y qemu-user-static tesseract-ocr libtesseract-dev
           pip install -U pip setuptools
-          pip install -r ${{ inputs.test_dir }}/requirements.txt
+          pip install -r "${{ needs.call_get_app_metadata.outputs.pytest_directory }}/requirements.txt"
 
       - name: Run test
         env:
           CTEST_OUTPUT_ON_FAILURE: 1
-        run: pytest ${{ inputs.test_dir }}/ --tb=short -v --device ${{ matrix.device }} -k ${{ inputs.test_filter }}
+        run: pytest ${{ needs.call_get_app_metadata.outputs.pytest_directory }}/ --tb=short -v --device ${{ matrix.device }} -k ${{ inputs.test_filter }}
 
       - name: Upload snapshots
         if: ${{ failure() && inputs.upload_snapshots_on_failure == true }}
         uses: actions/upload-artifact@v3
         with:
           name: ${{ matrix.device }}-tests-snapshots
-          path: ${{ inputs.test_dir }}/snapshots-tmp/${{ matrix.device }}
+          path: ${{ needs.call_get_app_metadata.outputs.pytest_directory }}/snapshots-tmp/${{ matrix.device }}
