get_app_metadata should only return [app] section info

diff --git a/.github/workflows/_get_app_metadata.yml b/.github/workflows/_get_app_metadata.yml
--- a/.github/workflows/_get_app_metadata.yml
+++ b/.github/workflows/_get_app_metadata.yml
@@ -27,15 +27,15 @@ on:
         required: false
         default: 'None'
         type: string
-      pytest_directory:
-        description: |
-          The directory where the Python tests are stored (a `conftest.py` file is expected there).
+      # pytest_directory:
+      #   description: |
+      #     The directory where the Python tests are stored (a `conftest.py` file is expected there).
 
-          If the application is configured with a 'ledger_app.toml' manifest at its root with a
-          'tests.pytest_directory' field, this parameter is ignored.
-        required: false
-        default: 'None'
-        type: string
+      #     If the application is configured with a 'ledger_app.toml' manifest at its root with a
+      #     'tests.pytest_directory' field, this parameter is ignored.
+      #   required: false
+      #   default: 'None'
+      #   type: string
     outputs:
       is_rust:
         description: Returns "true" if the app is using Rust SDK, else returns "false"
@@ -49,10 +49,10 @@ on:
         description:
           The list of device(s) supported by the application.
         value: ${{ jobs.fetch_metadata.outputs.compatible_devices }}
-      pytest_directory:
-        description: |
-          The directory where the Python tests are stored (a `conftest.py` file is expected there).
-        value: ${{ jobs.fetch_metadata.outputs.pytest_directory }}
+      # pytest_directory:
+      #   description: |
+      #     The directory where the Python tests are stored (a `conftest.py` file is expected there).
+      #   value: ${{ jobs.fetch_metadata.outputs.pytest_directory }}
 
 env:
   APP_MANIFEST: "ledger_app.toml"
@@ -118,13 +118,13 @@ jobs:
           echo "compatible_devices=${compatible_devices}" | sed 's/+/p/' >> "$GITHUB_OUTPUT"
 
           # pytest_directory (if any)
-          set +e  # when [tests.pytest_directory] is not set, ledger-manifest fails. We don't want that
-          if temp="$(ledger-manifest --output-pytest-directory -j "$APP_MANIFEST" | jq -rc '.pytest_directory')";
-          then
-              pytest_directory="${temp}"
-          fi
-          set -e
-          echo "pytest_directory=${pytest_directory}" >> "$GITHUB_OUTPUT"
+          # set +e  # when [tests.pytest_directory] is not set, ledger-manifest fails. We don't want that
+          # if temp="$(ledger-manifest --output-pytest-directory -j "$APP_MANIFEST" | jq -rc '.pytest_directory')";
+          # then
+          #     pytest_directory="${temp}"
+          # fi
+          # set -e
+          # echo "pytest_directory=${pytest_directory}" >> "$GITHUB_OUTPUT"
 
           # SDK language
           if [ "$(ledger-manifest --output-sdk "$APP_MANIFEST")" = "rust" ];
@@ -141,4 +141,4 @@ jobs:
       is_rust: ${{ steps.fetch_metadata.outputs.is_rust }}
       compatible_devices: ${{ steps.fetch_metadata.outputs.compatible_devices }}
       build_directory: ${{ steps.fetch_metadata.outputs.build_directory }}
-      pytest_directory: ${{ steps.fetch_metadata.outputs.pytest_directory }}
+      # pytest_directory: ${{ steps.fetch_metadata.outputs.pytest_directory }}
