Update reusable swap test wf so it can be called by Exchange

diff --git a/.github/workflows/reusable_swap_tests.yml b/.github/workflows/reusable_swap_tests.yml
--- a/.github/workflows/reusable_swap_tests.yml
+++ b/.github/workflows/reusable_swap_tests.yml
@@ -14,7 +14,9 @@ on:
         default: ${{ github.ref }}
         type: string
       download_app_binaries_artifact:
-        required: true
+        required: false
+        default: ''
+        description: 'If not provided, the workflow will build the app to test.'
         type: string
       exchange_build_artifact:
         required: false
@@ -31,12 +33,22 @@ on:
         default: false
         type: boolean
       swap_test_dir:
-        required: true
-        description: 'The directory where the swap tests are located.'
+        required: false
+        default: ''
+        description: 'The directory where the swap tests are located. If not provided, the workflow will find it automatically.'
         type: string
 
 
 jobs:
+  build_app:
+    name: Build app to test using the reusable workflow
+    if: ${{ inputs.download_app_binaries_artifact == '' }}
+    uses: ./.github/workflows/reusable_build.yml
+    with:
+      app_repository: ${{ inputs.app_repository }}
+      app_branch_name: ${{ inputs.app_branch_name }}
+      upload_app_binaries_artifact: "app_binaries"
+
   build_exchange:
     name: Build Exchange app using the reusable workflow
     if: ${{ inputs.exchange_build_artifact == '' }}
@@ -93,21 +105,54 @@ jobs:
           echo "Exchange build artifact: ${{ steps.get_exchange_binaries.outputs.exchange_build_artifact }}"
           echo "Ethereum build artifact: ${{ steps.get_ethereum_binaries.outputs.ethereum_build_artifact }}"
 
+  get_swap_test_dir:
+    name: Find swap test directory
+    if: ${{ inputs.swap_test_dir == '' }}
+    runs-on: ubuntu-latest
+    outputs:
+      swap_test_dir: ${{ steps.find_swap_test_dir.outputs.swap_test_dir }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ inputs.app_repository }}
+          ref: ${{ inputs.app_branch_name }}
+          path: app_coin
+      - name: Install ledgered
+        run: |
+          python3 -m pip install ledgered
+      - name: Find swap test directory
+        id: find_swap_test_dir
+        run: |
+          cd app_coin
+          # Get the swap test directory using ledger-manifest and jq
+          swap_test_dir=$(ledger-manifest --output-pytest-directories -j -- ledger_app.toml | jq -r '.pytest_directories[1]')
+          if [ -z "$swap_test_dir" ]; then
+            echo "Swap test directory not found!" >&2
+            exit 1
+          fi
+          echo "swap_test_dir=$swap_test_dir" >> "$GITHUB_OUTPUT"
+      - name: Show found swap test directory
+        run: |
+          echo "Display found swap test directory"
+          echo "Found swap test directory: ${{ steps.find_swap_test_dir.outputs.swap_test_dir }}"
+
   get_dir_names:
     name: Build artifact destination directories
+    needs: get_swap_test_dir
     runs-on: ubuntu-latest
     outputs:
       swap_test_dir: ${{ steps.get_swap_test_dir.outputs.swap_test_dir }}
       main_app_dir: ${{ steps.get_swap_test_dir.outputs.main_app_dir }}
       lib_app_dir: ${{ steps.get_swap_test_dir.outputs.lib_app_dir }}
     steps:
-      - name: Get swap test directory
+      - name: Set swap test directories
         id: get_swap_test_dir
         run: |
-          echo "swap_test_dir=${{ inputs.swap_test_dir }}" >> "$GITHUB_OUTPUT"
-          echo "main_app_dir=${{ inputs.swap_test_dir }}/.test_dependencies/main/app-exchange/build" >> "$GITHUB_OUTPUT"
-          echo "lib_app_dir=${{ inputs.swap_test_dir }}/.test_dependencies/libraries/app-ethereum/build" >> "$GITHUB_OUTPUT"
-      - name: Show swap test directory
+          echo "swap_test_dir=${{ (inputs.swap_test_dir != '' && inputs.swap_test_dir) || needs.get_swap_test_dir.outputs.swap_test_dir }}" >> "$GITHUB_OUTPUT"
+          echo "main_app_dir=${{ (inputs.swap_test_dir != '' && inputs.swap_test_dir) || needs.get_swap_test_dir.outputs.swap_test_dir }}/.test_dependencies/main/app-exchange/build" >> "$GITHUB_OUTPUT"
+          echo "lib_app_dir=${{ (inputs.swap_test_dir != '' && inputs.swap_test_dir) || needs.get_swap_test_dir.outputs.swap_test_dir }}/.test_dependencies/libraries/app-ethereum/build" >> "$GITHUB_OUTPUT"
+      - name: Show swap test directories
         run: |
           echo "Swap test directory: ${{ steps.get_swap_test_dir.outputs.swap_test_dir }}"
           echo "Main app directory: ${{ steps.get_swap_test_dir.outputs.main_app_dir }}"
@@ -122,7 +167,7 @@ jobs:
     with:
       app_repository: ${{ inputs.app_repository }}
       app_branch_name: ${{ inputs.app_branch_name }}
-      download_app_binaries_artifact: ${{ inputs.download_app_binaries_artifact }}
+      download_app_binaries_artifact: ${{ inputs.download_app_binaries_artifact != '' && inputs.download_app_binaries_artifact || 'app_binaries' }}
       additional_app_binaries_artifact: ${{ needs.get_artifacts_names.outputs.exchange_build_artifact }}
       additional_app_binaries_artifact_dir: ${{ needs.get_dir_names.outputs.main_app_dir }}
       lib_binaries_artifact: ${{ needs.get_artifacts_names.outputs.ethereum_build_artifact }}
